//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj2.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faaliyet
    {
        public int Faaliyet_id { get; set; }
        public string Faaliyet_tür { get; set; }
        public string Konu { get; set; }
        public string Faaliyet_sahibi { get; set; }
        public string Faaliyet_atayan { get; set; }
        public string Oluşturma_tarih { get; set; }
        public string Proje { get; set; }
        public string Önem_derecesi { get; set; }
        public string Açıklama { get; set; }
        public string Öngörülen_başlama { get; set; }
        public string Öngörülen_bitiş { get; set; }
        public string İlgili_kurum { get; set; }
    }
}
