//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj2.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faaliyet_türü
    {
        public int Faaliyet_id { get; set; }
        public string Faaliyet_tür { get; set; }
    }
}
