//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj2.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public string Tc { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Kuladi { get; set; }
        public string Sifre { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Aciltel { get; set; }
        public string Cinsiyet { get; set; }
        public string Doğum { get; set; }
        public string Medeni { get; set; }
        public string Kultip { get; set; }
        public string Kulil { get; set; }
        public string Kulilçe { get; set; }
        public string Adres { get; set; }
        public string İban { get; set; }
        public string Başlama { get; set; }
        public string Ayrılma { get; set; }
        public string Okul { get; set; }
        public string Bölüm { get; set; }
        public byte[] Resim { get; set; }
    }
}
