//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staj2.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class loginEntities1 : DbContext
    {
        public loginEntities1()
            : base("name=loginEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faaliyet> Faaliyet { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<Faaliyet_türü> Faaliyet_türü { get; set; }
    }
}
